wcandillon/react-native-redash

src/Colors.ts

fix(🎨): fix bug in color interpolation

---

src/AnimationRunners.ts

After much trial and error (and learning) I finally figured out how to reset the animation timer when a value changes. This looks and feels much nicer than having the frame timer keep running when the `toValue` changes.
I'm sure it can be improved on, but I thought I'd shine a flashlight on this, and let you decide if it's worth making an actual change. If so, it probably has equivalent solutions in the other animation functions.
I've attached my messy scratch-pad code if you would like to try it out (add imports etc before running the code).
```
function runTiming2(clock, value, config) {
const state = {
finished: new Value(0),
position: new Value(0),
time: new Value(0),
frameTime: new Value(0)
};
return block([
onChange(config.toValue, set(state.frameTime, 0)),
cond(clockRunning(clock), …
```

Reset frame time when toValue changes

---

README.md
src/Colors.ts
src/SVG.ts

💄 Improvements in SVG Path Morphing

---

README.md
package.json
src/Animations.ts
src/Gesture.ts
yarn.lock

BREAKING CHANGE: This changes the return type of `gestureEvent()` to allow for this syntax: `<PanGestureHandler {...onGestureEvent}>`.

fix(💄): add convenience to gestureEvent

---

src/Interactable.tsx
src/index.ts

I wanted to extend `InteractableProps`.

feat(📤): export interface `InteractableProps`

---

src/Gesture.ts

fix(👋🏻): Minor improvement in preserveOffset

---

src/Gesture.ts

feat(👋🏻): Exposes x and y values via panGestureHandler()

---

src/String.tsx

fix(🐛): fix string() on Android

---

README.md
src/Animations.ts

fix(🐛): Fix substancial bug in useTransition

---

README.md
src/AnimationRunners.ts
src/Gesture.ts
yarn.lock

[Toggle Preview](https://snack.expo.io/@dsznajder/toggle-animation-runner)
I've added toggle runner as I think this can be useful for people when you would like to run animations from `onPress` event

feat(📦): Add toggle runner

---

README.md
src/AnimationRunners.ts

also fixes https://github.com/wcandillon/react-native-redash/issues/130

fix(📖): loop doc

---

README.md
package.json
src/Colors.ts
yarn.lock

Closes https://github.com/wcandillon/react-native-redash/issues/88

feat(✨): allow using hex strings

---

README.md
src/Math.ts
src/bezier/CubicBezierSolve.ts

Breaking Change: Remove functions that can now be used directly from Reanimated.

fix(♾): Remove functions that can now be used directly from Reanimated

---

README.md

See:
- https://github.com/wcandillon/react-native-redash/blob/master/src/Gesture.ts#L239
- https://github.com/wcandillon/react-native-redash/blob/master/src/Gesture.ts#L265
- https://github.com/wcandillon/react-native-redash/blob/master/src/Gesture.ts#L284

fix(📖): gesture docs

---

src/Animations.ts

feat: Add useClocks

---

packages/core/src/AnimationRunners.ts

fix(🐛): fix type for decay() and spring()

---

packages/core/src/Hooks.ts

fix(⬇️): Revert to the old reanimated import style

---

package.json
src/ReText.tsx
src/index.d.ts
src/v1/Colors.ts
src/v1/SVG.ts
yarn.lock

fix(🐛): Fix support for reanimated 2.1.0

---

src/Matrix3.ts
src/Transforms.ts
src/__tests__/Matrix3.test.ts
tsconfig.json

fix(🧮): Fix 2d transform type

---

src/ReText.tsx

Allow passing arbitrary props to ReText component

---

src/ReText.tsx

Reverts wcandillon/react-native-redash#512

Revert "added dependency List to ReText 4 RNweb animations"
