- src/Interactable.tsx
BREAKING CHANGE: the unsupported `snapTo` method from `<Interactable>`  has been removed.
> fix(📦): disable non support snapTo method

- README.md
- src/Colors.ts
It would be great to be able to choose the color space for interpolation since it yields different results depending on which color space you use. I prefer the look of interpolating in RGB (and it's cheap!) since HSV interpolation can introduce "flashes" of other colors.
You can see in the GIF that HSV interpolation shows a green color in the middle of interpolating between blue and yellow, and blue between cyan and magenta.
This also happens in RGB (blue -> yellow has a gray color in the middle), but I think it's a less jarring look.
> Add option to choose RGB or HSV for interpolation

- README.md
Since we don't have the capacity to support this component at the moment. I would like to remove its mention from the documentation. I found the other functions provided by redash powerful enough to build complex gestures without `<Interactable>`.
> fix(📚): Remove the mention of <Interactable>

- src/AnimationRunners.ts
I took the platform default from https://facebook.github.io/react-native/docs/scrollview#decelerationrate 🤷🏼‍♂️
> fix(🐛): Make decay configuration and use platform defaults

- README.md
- src/Colors.ts
BREAKING CHANGE: The default color space for interpolation is now RGB.
> fix(🎨): Switch default color space to rgb

- README.md
- src/AnimationRunners.ts
@dsznajder This is how I would like the animations runner to look like in the future: 
* They should all be interruptable
* All parameters that could be optional should be optional
* Remove the `run` prefix
* We use name parameters in order to deal with the optional parameters more gracefully.
What are your thoughts on this?
> feat(⏰): Interruptible loop()

- src/AnimationRunners.ts
The user can optionally pass in a SpringConfig property to configure the stiffness, mass, and stiffness of a spring animation. Currently, they must pass in all properties if you want to change one of them, otherwise they will get an error in TypeScript. However, as the options are spread along with default values the user should be able to pass in just the properties they would like to change from the default.
This commit changes the type signature of the SpringConfig property to accept a Partial. This allows you to change from this code:
```
spring({
from: dest,
to: src,
velocity,
config: {
damping: 6,
mass: 1,
stiffness: 100,
overshootClamping: false,
restSpeedThreshold: 0.01,
restDisplacementThreshold: 0.01,
}
})
```
to this code:
```
spring({
from: dest,
to: src,
velocity,
config: { …
```
> feat: Allow partial SpringConfig when defining a spring animation

- README.md
Just copied this and noticed a comma is missing in the README..
Spending this afternoon experimenting a bit, hopefully will be able to post a cool demo soon :) 
Cheers!
> Fix missing comma in example in README

- src/SVG.ts
This address the issue with the unexpectedData red scree when attempting to use interpolatePath found here, https://github.com/wcandillon/react-native-redash/issues/154.
However, I have noticed, that when using this animating svg paths with this method combined with reanimated, they are not native, but javascript. I checked older versions of this, and checked previous Can It Be Done With React Native SVG animations like (https://github.com/wcandillon/can-it-be-done-in-react-native/tree/master/season3/src/LiquidSwipe) and notice these are also javascript animations (with many bridge crossings).
I am not sure if this is the intention or a restriction with animated svgs with reanimated, but this PR will re-align the interpolatePath function as it was previously, and allow animated SVG paths.
> Fix interpolatePath unexpectedData error

- packages/docs/src/gestures.mdx
Quick fix to make `onGestureEvent()` searchable in the dos
> Fix: `onGestureEvent()` link in docs

- src/Colors.ts
Hi there 👋,
I notice that `interpolateColor` was having an issue with interpolating the alpha value, then i notice that the value been rounded 👇
```
const a = round(
interpolate(animationValue, {
inputRange,
outputRange: colors.map(c => opacity(c)),
extrapolate: Extrapolate.CLAMP
})
);
```
so i just removed it and it fix the issue 😀
> Fix interpolateColor alpha interpolate value

- packages/docs/src/gestures.mdx
`onScroll` no longer exists so this has to be updated in the docs as well.
> Fix docs for `onScrollEvent`

- packages/core/package.json
As a first time contributor: thanks for your library! As far as I can see we can mark this library as side effect free to improve tree shaking: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> fix: mark side effect free

- packages/docs/src/transformations.mdx
Found a docs bug: The actual API has only two arguments and requires a `Point` as the first one.
> Fix `transformOrigin` example

- packages/core/src/Transitions.ts
I noticed that currently, the clock of spring and timing is never stopping thus the evaluation is happening all the time. It's nothing wrong when we have few components, but in my case, I'm extensively using those helpers across the app and noticed that native UI thread on Android is blocked by the number of operations. 
because more or less 50 evaluations are happening simultaneously.
I changed the way of evaluating to stop the clock when the animation is finished and start again of needed and noticed the boost of performance. 
(got rid of grey part responsible for reanimated methods)
I use already forked version with these changes in my app.
> Optimize useSpringTrasition and useTimingTransition

- packages/docs/src/vectors.mdx
Hi, recently I'm watching PinchGesture video, and I find that `vec.invert` is no longer in the codebase but still in the document, and this is because this function was renamed, so I patch the doc and open this pull request.
> fix(doc): update function rename in Vector doc

- src/v1/Colors.ts
Upgraded to v15 and all of our interpolateColor usages went berserk. Dig some digging and noticed [this change](https://github.com/wcandillon/react-native-redash/commit/3933f50465504bcf892cc74af09aa65a9ad119a0#diff-b5b730b0df3fd3b446d93242798ee74cR3). I think the removal of the extrapolation clamping is unintentional.
> v1 InterpolateColors Regression

- src/Paths.ts
- src/__tests__/Paths.test.ts
> fix(🐛): getXforY() now returns null if x is out of bound

- src/Paths.ts
Reanimated v3 removes the v1 implementation. The Animated.Extrapolate enum is part of what was removed. Instead there is the `Extrapolation` enum we can use. The only potential issue is it was only introduced in reanimated@2.3.0 (https://github.com/software-mansion/react-native-reanimated/commit/cb651ecf9b6d4df715ab7da4686f66140e5f13a3). Another potential solution to support both would be to use string literals instead of the enum.
> Use Extrapolation enum instead of Animated.Extrapolate to support reanimated v3

- src/ReText.tsx
So, 
While Using ReText with RNweb, It's required to pass a dependency List to useAnimatedProps and some other hooks 
as in the dox [Web without the Babel plugin](https://docs.swmansion.com/react-native-reanimated/docs/guides/web-support#web-without-the-babel-plugin)
A simple change to `/src/ReText.tsx`
```
const animatedProps = useAnimatedProps(() => {
return {
text: text.value,
...
} as any;
}, [text]);  // <-- added this to the  dependency List [text] that's it
```
hope it gets merged soon,
currently using it vie yarn patch packages
> added dependency List to ReText 4 RNweb animations

- src/ReText.tsx
Reanimated in strict mode (default) gives a warning when the parent component using ReText is re-rendered:
> WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.
This is because it's reading `text.value` directly in the component body (for the initial value). `useMemo` can be used to explicitly get the first value as a React value.
> fix(💄): Prevent reading from sharedValue during component render
